image_finetune: false

output_dir: "outputs"
pretrained_model_path: "models/StableDiffusion/stable-diffusion-v1-5"
dataset_name: 'shutterstock'

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  image_condition_dim            : 1024
  use_ip_cross_attention         : True
  scale                          : 1.0
  num_tokens                     : 4

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  csv_path: 
    - "YOUR PATH/share_1367250/0_public_datasets/shutterstock_6M/shutterstock_450w_new_nocr.csv"
    - "YOUR PATH/share_1367250/0_public_datasets/webvid-10m/annotations/results_10M_train.csv"
  video_folder: 
    - "YOUR PATH/share_1629729/0_public_datasets/shutterstock/videos"
    - "YOUR PATH/share_1367250/0_public_datasets/webvid-10m/videos"
  sample_size:     
    - 256
    - 448
  sample_stride:   4
  sample_n_frames: 16

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 40
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."
  - "to_k_ip"
  - "to_v_ip"
  - "image_proj_model"

unet_checkpoint_path: "outputs/training_14M_448x256_w_multi_scale_w_image_cond-2023-09-18T14-48-47/checkpoints/checkpoint-136000.ckpt"

learning_rate:    1.e-5
train_batch_size: 3

max_train_epoch:      -1
max_train_steps:      1000000
checkpointing_epochs: -1
checkpointing_steps:  2000

validation_steps:       100
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True
gradient_checkpointing: True

use_ip_cross_attention : True
image_pretrained_model_path : "/mnt/apdcephfs/share_1367250/jacobkong/gitpackages/huggingface_models/IP-Adapter/models/image_encoder"
# ip_pretrained_model_path : "/mnt/apdcephfs/share_1367250/jacobkong/gitpackages/huggingface_models/IP-Adapter/models/ip-adapter_sd15.bin"
unet_base_checkpoint_path: "outputs/image_finetune_14M-2023-08-31T17-04-41/checkpoints/checkpoint-18000.ckpt"
use_temporal_multi_scale_training: True


is_debug: False
