image_finetune: false

output_dir: "outputs"
pretrained_model_path: "models/StableDiffusion/stable-diffusion-2-1"
# pretrained_model_path: "models/StableDiffusion/stable-diffusion-v1-5"
# motion_pretrained_model_path: "outputs/training_14M_448x256_w_multi_scale_w_fps_sd_v2.1-2023-11-08T20-48-18/checkpoints/checkpoint-2000.ckpt"
dataset_name: 'shutterstock'

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false
  use_linear_projection          : true
  use_inflated_groupnorm         : true
  motion_module_mid_block        : true
  use_fps_condition              : true
  use_temporal_conv              : true
  # use_pseudo_conv3d              : true

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false
  prediction_type:     "v_prediction"

train_data:
  csv_path: 
    # - "YOUR PATH/share_1367250/0_public_datasets/shutterstock_6M/shutterstock_450w_new_nocr.csv"
    - "YOUR PATH/share_1367250/0_public_datasets/webvid-10m/annotations/results_10M_val.csv"
    # - "YOUR PATH/share_1629729/0_public_datasets/HD-VG-130M/all_info_filtered.csv"
    # - "YOUR PATH/share_1367250/0_public_datasets/pexels_video/pexel_data_info.csv"
  video_folder: 
    # - "YOUR PATH/share_1629729/0_public_datasets/shutterstock/videos"
    - "YOUR PATH/share_1367250/0_public_datasets/webvid-10m/videos"
    # - "YOUR PATH/share_1629729/0_public_datasets/HD-VG-130M/video_clips"
    # - "YOUR PATH/share_1367250/0_public_datasets/pexels_video/videos_compress"
  sample_size:     
    - 320
    - 512
  sample_stride  : 4
  sample_n_frames: 16
  dynamic_fps    : True
  add_static_image: True

validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 40
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."
  - "fps"
  - "temporal"


learning_rate:    5.e-5
train_batch_size: 1

max_train_epoch:      -1
max_train_steps:      2000000
checkpointing_epochs: -1
checkpointing_steps:  2000

validation_steps:       100
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True
gradient_checkpointing: True

use_temporal_multi_scale_training: True
use_fps_condition: true
# use_spatial_temporal_separate_lr: true

is_debug: False
