#flag tag
image_finetune: false

output_dir: "Output_dir"
pretrained_model_path: "stable-diffusion-v1-5"  #SD-1.5  PATH
motion_pretrained_model_path: "/teg_amai_sh_1/share_301124792/antonwang/cache/256x256_st_unet/checkpoints/checkpoint-208000.ckpt"
unet_checkpoint_path: "/teg_amai_cq5_1/share_1629729/antonwang/experiments/AnimateDiff_it2v/training_14M_512x512_part_img_embed_mask_condition_zero_snr_sd1.5_img_as_vid_for_train_all_parameters-2024-01-17T10-30-38/checkpoints/checkpoint-76000.ckpt"

unet_base_checkpoint_path: "stable-diffusion-v1-5"   #SD-1.5  PATH


dataset_name: 'webvid'

use_first_frame_mask_condition_concat : true
use_first_frame_mask_condition_concat_need_for_validation : false
use_frame_conditioning_corruption: true
use_first_frame_mask_condition_concat_image_mask_rate : [0, 0.3, 0.5, 0.7]

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false
  use_fps_condition              : true
  use_first_frame_mask_condition_concat : true

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false
  prediction_type:     "v_prediction"
  rescale_betas_zero_snr: true

train_data:
  csv_path:
   "Webvid-dataset.csv"



  video_folder: 
    "/teg_amai_2/share_1367250/0_public_datasets/webvid-10m/videos"
    
  sample_size:     
    - 512
    - 512
  sample_stride:   4
  sample_n_frames: 24
  dynamic_fps: true


validation_data:
  prompts:
    - "Snow rocky mountains peaks canyon. Snow blanketed rocky mountains surround and shadow deep canyons."
    - "A drone view of celebration with Christma tree and fireworks, starry sky - background."
    - "Robot dancing in times square."
    - "Pacific coast, carmel by the sea ocean and waves."
  num_inference_steps: 40
  guidance_scale: 8.

trainable_modules:
  - "motion_modules."
  - "conv_in"
  - "motion_embedding"
  - "fps"


learning_rate:    1.e-5
train_batch_size: 3

max_train_epoch:      -1
max_train_steps:      50000
checkpointing_epochs: -1
checkpointing_steps:  2000
need_resume : true

validation_steps:       50
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true
enable_xformers_memory_efficient_attention: True
gradient_checkpointing: True

use_temporal_multi_scale_training: True
use_fps_condition: true
use_spatial_temporal_separate_lr: false  # if true, all parameters train

is_debug: False
